### ISSUE TITLE
ArrayCollection Deserialization problem

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mondain/red5#187]
```
What steps will reproduce the problem?
1.Create Two remote classes that implement IExternalizable
One remote class contains an ArrayCollection of the second class
2.Make a remote procedure call from flex to Red5 server with an ArrayCollection 
of the "parent" class as argument

What is the expected output? What do you see instead?
The server is unable to deserialize the input when the "parent" class has more 
than one child.
In the red5.log you can see "org.red5.io.amf3.Input - Unknown datatype:xx" 

What version of the product are you using? On what operating system?
Red5 1.0.0 RC1

Please provide any additional information below.

My java and as3 classes are attached below.

```

Original issue reported on code.google.com by `kevin.ri...@gmail.com` on 13 Mar 2012 at 2:30
- Blocked on: #151

Attachments:
- [red5.log](https://storage.googleapis.com/google-code-attachments/red5/issue-187/comment-0/red5.log)
- [Requirement.java](https://storage.googleapis.com/google-code-attachments/red5/issue-187/comment-0/Requirement.java)
- [RequirementSet.java](https://storage.googleapis.com/google-code-attachments/red5/issue-187/comment-0/RequirementSet.java)
- [Requirement.as](https://storage.googleapis.com/google-code-attachments/red5/issue-187/comment-0/Requirement.as)
- [RequirementSet.as](https://storage.googleapis.com/google-code-attachments/red5/issue-187/comment-0/RequirementSet.as)

**Comment by qickrooms** [comment]
Hi, I am having the exact same issue as above, I have the very latest build 1.0.7 (12 May) and Red5Pro (older version) too.

I used the sample flex / java code above and my own code to confirm still an issue.

Here is the log for my classes:

` 2016-05-18 15:09:31,276 [main] INFO  o.a.coyote.http11.Http11NioProtocol - Starting ProtocolHandler ["http-nio-0.0.0.0-5080"]
2016-05-18 15:09:31,300 [main] INFO  org.red5.server.tomcat.TomcatLoader - Context initialized:  path: D:\Red5-server-1.0.7\webapps\root\
2016-05-18 15:09:31,306 [main] INFO  org.red5.server.tomcat.TomcatLoader - Context initialized: /dciNotifications path: D:\Red5-server-1.0.7\webapps\dciNotifications\
2016-05-18 15:09:31,311 [main] INFO  org.red5.server.tomcat.TomcatLoader - Dedicated RTMPT server configuration was not specified
2016-05-18 15:09:31,316 [main] INFO  org.red5.server.ContextLoader - JEE server was found: TomcatLoader [serviceEngineName=red5Engine]
2016-05-18 15:09:31,323 [pool-5-thread-1] INFO  o.s.w.c.s.XmlWebApplicationContext - Refreshing Root WebApplicationContext: startup date [Wed May 18 15:09:31 AEST 2016]; parent: org.springframework.context.support.FileSystemXmlApplicationContext@4248ed58
2016-05-18 15:09:31,336 [main] INFO  o.red5.server.plugin.PluginLauncher - Loaded plugin: org.red5.net.websocket.WebSocketPlugin
2016-05-18 15:09:31,341 [pool-5-thread-1] INFO  o.s.b.f.xml.XmlBeanDefinitionReader - Loading XML bean definitions from ServletContext resource [/WEB-INF/red5-web.xml]
2016-05-18 15:09:31,388 [main] INFO  o.r.n.websocket.WebSocketTransport - WebSocket (ws) will be bound to [0.0.0.0:8081]
2016-05-18 15:09:31,401 [pool-5-thread-1] INFO  o.s.b.f.c.PropertyPlaceholderConfigurer - Loading properties file from ServletContext resource [/WEB-INF/red5-web.properties]
2016-05-18 15:09:31,409 [main] INFO  o.r.n.websocket.WebSocketTransport - started  websocket transport
2016-05-18 15:09:31,418 [pool-5-thread-1] INFO  org.red5.server.Context - Setting parent bean factory as core
2016-05-18 15:09:31,436 [pool-5-thread-1] INFO  org.red5.server.scope.WebScope - Set server [Server@608c7d82map[[empty]]]
2016-05-18 15:09:31,450 [pool-5-thread-1] INFO  org.red5.server.scope.Scope - Scope null name reset to:  disallowed
2016-05-18 15:09:31,460 [pool-5-thread-1] INFO  org.red5.server.Server - Add mapping global: default host:  context: null
2016-05-18 15:09:31,464 [pool-5-thread-1] INFO  org.red5.server.scope.Scope - Invalid scope name, null is not allowed
2016-05-18 15:09:31,467 [pool-5-thread-1] WARN  org.red5.server.scope.Scope - Invalid scope rejected: Scope [name=null, path=/default, type=APPLICATION, autoStart=true, creationTime=1463548171428, depth=1, enabled=true, running=false]
2016-05-18 15:09:31,475 [pool-5-thread-1] WARN  org.red5.server.scope.Scope - Scope not added to parent
2016-05-18 15:09:31,477 [pool-5-thread-1] INFO  org.red5.server.scope.WebScope - Webscope already registered
2016-05-18 15:09:31,489 [pool-5-thread-1] INFO  o.s.w.c.s.XmlWebApplicationContext - Refreshing Root WebApplicationContext: startup date [Wed May 18 15:09:31 AEST 2016]; parent: org.springframework.context.support.FileSystemXmlApplicationContext@4248ed58
2016-05-18 15:09:31,499 [pool-5-thread-1] INFO  o.s.b.f.xml.XmlBeanDefinitionReader - Loading XML bean definitions from ServletContext resource [/WEB-INF/red5-web.xml]
2016-05-18 15:09:31,559 [pool-5-thread-1] INFO  o.s.b.f.c.PropertyPlaceholderConfigurer - Loading properties file from ServletContext resource [/WEB-INF/red5-web.properties]
2016-05-18 15:09:31,574 [pool-5-thread-1] INFO  org.red5.server.Context - Setting parent bean factory as core
2016-05-18 15:09:31,580 [pool-5-thread-1] INFO  org.red5.server.scope.WebScope - Set server [Server@608c7d82map['/' -> 'default']]
2016-05-18 15:09:31,599 [pool-5-thread-1] INFO  org.red5.server.Server - Add mapping global: default host:  context: dciNotifications
2016-05-18 15:09:31,607 [pool-5-thread-1] INFO  org.red5.server.Server - Add mapping global: default host: localhost context: dciNotifications
2016-05-18 15:09:31,611 [pool-5-thread-1] INFO  org.red5.server.Server - Add mapping global: default host: localhost:8088 context: dciNotifications
2016-05-18 15:09:31,616 [pool-5-thread-1] INFO  org.red5.server.Server - Add mapping global: default host: 127.0.0.1:8088 context: dciNotifications
2016-05-18 15:09:31,622 [pool-5-thread-1] INFO  org.red5.server.Server - Add mapping global: default host: 192.168.0.21 context: dciNotifications
2016-05-18 15:09:31,627 [pool-5-thread-1] INFO  org.red5.server.Server - Add mapping global: default host: 192.168.0.100 context: dciNotifications
2016-05-18 15:09:31,802 [pool-5-thread-1] INFO  c.h.instance.DefaultAddressPicker - [LOCAL] [dev] [3.5] Prefer IPv4 stack is true.
2016-05-18 15:09:31,966 [pool-5-thread-1] INFO  c.h.instance.DefaultAddressPicker - [LOCAL] [dev] [3.5] Picked Address[192.168.75.1]:5701, using socket ServerSocket[addr=/0:0:0:0:0:0:0:0,localport=5701], bind any local is true
2016-05-18 15:09:32,536 [pool-5-thread-1] INFO  com.hazelcast.spi.OperationService - [192.168.75.1]:5701 [dev] [3.5] Backpressure is disabled
2016-05-18 15:09:32,568 [pool-5-thread-1] INFO  c.h.s.i.o.c.ClassicOperationExecutor - [192.168.75.1]:5701 [dev] [3.5] Starting with 2 generic operation threads and 4 partition operation threads.
2016-05-18 15:09:33,489 [pool-5-thread-1] INFO  com.hazelcast.system - [192.168.75.1]:5701 [dev] [3.5] Hazelcast 3.5 (20150617 - 4270dc6) starting at Address[192.168.75.1]:5701
2016-05-18 15:09:33,501 [pool-5-thread-1] INFO  com.hazelcast.system - [192.168.75.1]:5701 [dev] [3.5] Copyright (c) 2008-2015, Hazelcast, Inc. All Rights Reserved.
2016-05-18 15:09:33,840 [pool-5-thread-1] INFO  com.hazelcast.instance.Node - [192.168.75.1]:5701 [dev] [3.5] Creating MulticastJoiner
2016-05-18 15:09:33,853 [pool-5-thread-1] INFO  com.hazelcast.core.LifecycleService - [192.168.75.1]:5701 [dev] [3.5] Address[192.168.75.1]:5701 is STARTING
2016-05-18 15:09:36,147 [pool-5-thread-1] INFO  c.h.cluster.impl.MulticastJoiner - [192.168.75.1]:5701 [dev] [3.5] 

Members [1] {
    Member [192.168.75.1]:5701 this
}

2016-05-18 15:09:36,196 [pool-5-thread-1] INFO  com.hazelcast.core.LifecycleService - [192.168.75.1]:5701 [dev] [3.5] Address[192.168.75.1]:5701 is STARTED
2016-05-18 15:09:36,292 [pool-5-thread-1] INFO  org.red5.server.scope.WebScope - Webscope already registered
2016-05-18 15:09:36,308 [pool-5-thread-1] INFO  o.r.s.s.ApplicationSchedulingService - Application scheduler initializing...
2016-05-18 15:09:36,314 [pool-5-thread-1] INFO  org.quartz.impl.StdSchedulerFactory - Using default implementation for ThreadExecutor
2016-05-18 15:09:36,318 [pool-5-thread-1] INFO  o.quartz.core.SchedulerSignalerImpl - Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
2016-05-18 15:09:36,324 [pool-5-thread-1] INFO  org.quartz.core.QuartzScheduler - Quartz Scheduler v.2.2.2 created.
2016-05-18 15:09:36,327 [pool-5-thread-1] INFO  org.quartz.simpl.RAMJobStore - RAMJobStore initialized.
2016-05-18 15:09:36,330 [pool-5-thread-1] INFO  org.quartz.core.QuartzScheduler - Scheduler meta-data: Quartz Scheduler (v2.2.2) 'dciNotifications_Scheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 2 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

2016-05-18 15:09:36,345 [pool-5-thread-1] INFO  org.quartz.impl.StdSchedulerFactory - Quartz scheduler 'dciNotifications_Scheduler' initialized from an externally provided properties instance.
2016-05-18 15:09:36,350 [pool-5-thread-1] INFO  org.quartz.impl.StdSchedulerFactory - Quartz scheduler version: 2.2.2
2016-05-18 15:09:36,354 [pool-5-thread-1] INFO  org.quartz.core.QuartzScheduler - Scheduler dciNotifications_Scheduler_$_NON_CLUSTERED started.
2016-05-18 15:09:39,503 [RTMPConnectionExecutor-1] INFO  dci.application.dciApplication - W3C x-category:session x-event:connect c-ip:192.168.0.100 c-client-id:0
2016-05-18 15:09:40,359 [NioProcessor-3] ERROR org.red5.io.amf.Input - Error loading class: BuL$N
2016-05-18 15:09:40,369 [NioProcessor-3] WARN  o.r.s.n.r.codec.RTMPProtocolDecoder - Failed to decodeBuffer: pos 0, limit 2236, chunk size 128, buffer c3040506480202064943344631443930342d423738362d463443382d383041322d433234344546413133343230030203020203064c064938374238394342352d344238302d414336462d323133342d433234344546413145314144020a090303064931353441453433312d383537432d414430332d313542432d43323434454641c331334132440542754c244efa2000064946423932423830322d303135352d443432302d393545382d4332343445464131373631440a0d080142754c244efa10000a05090301060c0a05090301060e0a0509030106100402080142754c244efa10000a050903010612040104020a1106160618061a061c061e0620062206240626c3064945393935343237312d464545452d363232312d453834382d433234344546413139364630064932454537343036462d343832332d333943322d363346362d4332343445464131333543370a15090501062e063001064946413330453737452d373645442d323839392d454435382d43323434454641313841323406494645c34433424433432d363933332d333146462d393737322d433234344546413141453836064932323242363833382d303145392d333032312d394643372d433234344546413137433836064931303337373739412d433836362d464544452d313239352d433234344546413143444441064943443446303732382d334337322d3637c343342d373242312d433234344546413131423539064934433434333435312d374533312d353730332d384433452d433234344546413141433738064941334342424346322d454141342d304633302d353146382d43323434454641324539384201064936423743324543462d363336432d393942372d304145372d4332343445c346413241363734064934424133433535332d373042362d443536392d443236342d4332343445464132443843350542754c244efa20000542754c244efa2000040406440646040506480202064934384643424638332d334238312d463436302d323341362d433234344546413246304539030203020203064c06493739393344c33436352d373433312d303043462d413035392d433234344546413238384434020a090303064937393433463032362d463443442d353041442d423132322d4332343445464132463244320542754c244efa2000064944393938463846362d333644412d303433462d413833392d4332343445464132364542390a0d080142754cc3244efa20000a05090301060c0a05090301060e0a0509030106100402080142754c244efa20000a050903010612040104020a1106160618061a061c061e0620062206240626064945313635323238362d353442442d323038452d413244322d433234344546413239423836064933433734384543302d324132452d343142352dc3363641362d4332343445464132414341340a15090501062e063001064943464334333644452d344543332d313743432d344231422d433234344546413233373746064942323535434233412d434542352d324233332d454432332d433234344546413231443838064937463430443932442d354630362d413538432d41413030c32d433234344546413231443033064935373843373437442d433544422d343646392d384430452d433234344546413233443531064935414239464630302d313636302d463145362d374338442d433234344546413245354243064933423639464645342d454634302d303331362d323438322d43323434454641323143434106c34937323939444142462d373045302d353142312d373632392d43323434454641324643334501064937303346414534412d354244342d374433352d304343412d433234344546413235323731064945324143454535312d464630442d343539432d314635432d4332343445464132303234360542754c244efa20000542754c24c34efa2000040406440646040506480202064936304146424432392d443432442d384443462d383636392d433234344546413241433945030203020203064c064942434137413044432d364445342d454230392d383132422d433234344546413234303531020a090303064931363139453341322d433143392d343041462d3846c336462d4332343445464132384230340542754c244efa3000064935434635464444342d434146452d383430352d354442322d4332343445464132453345410a0d080142754c244efa30000a05090301060c0a05090301060e0a0509030106100402080142754c244efa30000a050903010612040104020a1106160618061a061cc3061e0620062206240626064946333139373441352d423946382d414630432d443038382d433234344546413338414335064936444446373543372d423146462d393233352d423242322d4332343445464133434641310a15090501062e063001064936303231314243442d413930332d384545432d373137362d433234344546c3413337323933064945303442333745322d344133362d323044462d443346432d433234344546413333303136064942334236464643352d413138412d344343432d373943422d433234344546413345323031064946314644443131372d423042462d464534442d324532432d4332343445464133383736390649463934453746c337432d423446352d394433442d374445442d433234344546413335333644064933413333454230422d314443462d413430432d383441302d433234344546413330354541064936433745383734412d443141362d424241362d373939452d43323434454641333345433301064936384134433645312d353337392d373741412dc3313641452d433234344546413346393834064941334131443430382d353543392d444236342d323043452d4332343445464133434238310542754c244efa30000542754c244efa3000040406440646040506480202064944323046373444332d373330412d464436312d413744432d4332343445464133333344460302030202c303064c064937434345313345422d373636412d333434302d384339432d43323434454641334635334202
2016-05-18 15:09:40,500 [NioProcessor-3] WARN  o.r.s.n.r.codec.RTMPProtocolDecoder - Closing connection because decoding failed: RTMPMinaConnection from 192.168.0.100 (in: 7573 out: 3287) session: HZPYS6OS6GWE2 state: connected
org.red5.server.net.protocol.ProtocolException: Error during decoding
    at org.red5.server.net.rtmp.codec.RTMPProtocolDecoder.decode(RTMPProtocolDecoder.java:202)
    at org.red5.server.net.rtmp.codec.RTMPProtocolDecoder.decodeBuffer(RTMPProtocolDecoder.java:127)
    at org.red5.server.net.rtmp.codec.RTMPMinaProtocolDecoder.decode(RTMPMinaProtocolDecoder.java:90)
    at org.apache.mina.filter.codec.ProtocolCodecFilter.messageReceived(ProtocolCodecFilter.java:230)
    at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:542)
    at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1300(DefaultIoFilterChain.java:48)
    at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:943)
    at org.red5.server.net.rtmpe.RTMPEIoFilter.messageReceived(RTMPEIoFilter.java:155)
    at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:542)
    at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1300(DefaultIoFilterChain.java:48)
    at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:943)
    at org.apache.mina.core.filterchain.IoFilterAdapter.messageReceived(IoFilterAdapter.java:109)
    at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:542)
    at org.apache.mina.core.filterchain.DefaultIoFilterChain.fireMessageReceived(DefaultIoFilterChain.java:535)
    at org.apache.mina.core.polling.AbstractPollingIoProcessor.read(AbstractPollingIoProcessor.java:697)
    at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:651)
    at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:640)
    at org.apache.mina.core.polling.AbstractPollingIoProcessor.access$600(AbstractPollingIoProcessor.java:68)
    at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:1097)
    at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.BufferUnderflowException: null
    at java.nio.HeapByteBuffer.get(HeapByteBuffer.java:151)
    at org.apache.mina.core.buffer.AbstractIoBuffer.get(AbstractIoBuffer.java:625)
    at org.apache.mina.core.buffer.AbstractIoBuffer.get(AbstractIoBuffer.java:1337)
    at org.red5.io.amf.Input.readString(Input.java:225)
    at org.red5.io.amf.Input.getString(Input.java:194)
    at org.red5.io.amf.Input.readPropertyName(Input.java:567)
    at org.red5.io.amf.Input.readKeyValues(Input.java:344)
    at org.red5.io.amf.Input.readSimpleObject(Input.java:500)
    at org.red5.io.amf.Input.readObject(Input.java:531)
    at org.red5.io.object.Deserializer.deserialize(Deserializer.java:97)
    at org.red5.io.amf.Input.readArray(Input.java:319)
    at org.red5.io.object.Deserializer.deserialize(Deserializer.java:88)
    at org.red5.server.net.rtmp.codec.RTMPProtocolDecoder.decodeFlexMessage(RTMPProtocolDecoder.java:1018)
    at org.red5.server.net.rtmp.codec.RTMPProtocolDecoder.decodeMessage(RTMPProtocolDecoder.java:493)
    at org.red5.server.net.rtmp.codec.RTMPProtocolDecoder.decodePacket(RTMPProtocolDecoder.java:299)
    at org.red5.server.net.rtmp.codec.RTMPProtocolDecoder.decode(RTMPProtocolDecoder.java:188)
    ... 22 common frames omitted
2016-05-18 15:09:40,615 [NioProcessor-3] INFO  dci.application.dciApplication - W3C x-category:session x-event:disconnect c-ip:192.168.0.100 c-client-id:0
2016-05-18 15:09:40,620 [NioProcessor-3] INFO  dci.application.dciApplication - W3C x-category:session x-event:disconnect c-ip:192.168.0.100 c-client-id:0
2016-05-18 15:09:40,629 [NioProcessor-3] INFO  o.r.s.net.rtmp.RTMPMinaConnection - Connection is closed: HZPYS6OS6GWE2
2016-05-18 15:09:40,633 [NioProcessor-3] WARN  o.r.s.net.rtmp.RTMPMinaIoHandler - Connection was not found for HZPYS6OS6GWE2
2016-05-18 15:10:18,499 [pool-4-thread-1] INFO  org.red5.server.tomcat.WarDeployer - Deploy wars with app start`

**Comment by qickrooms** [comment]
Confirmed, I have downloaded the latest red5pro, and this issue still appears. When there are complex objects with ArrayCollection in the child objects, there are de-serialisation issues, when the complex object is not as a child the de-serialisation error does not occur.
